Add rol student
alepervaz/Acme-L3-D02 pull request #42
Opened 2023-03-13 17:38 UTC by marvicmar

2023-03-15 18:13 UTC, alepervaz approved these changes
el código implementado esta completo y de forma correcta

2023-03-15 18:34 UTC, alesanfe requested changes
Las restricciones están mal, el máximo está incluido.

2023-03-15 22:22 UTC, alesanfe approved these changes

2023-03-16 07:33 UTC, alepervaz approved these changes
todo correcto

2023-03-16 07:33 UTC, merged