Task 5 (i3): add tutorial Entity
alepervaz/Acme-L3-D02 pull request #45
Opened 2023-03-15 17:57 UTC by alepervaz

2023-03-15 18:16 UTC, marvicmar requested changes
Cambiar el OneToMany por ManyToOne

2023-03-15 18:44 UTC, alesanfe requested changes
Qué es el List<Object>?

2023-03-16 09:15 UTC, marvicmar approved these changes
Ya esta correcta tras realizarle unas pequeñas correciones. Por otro lado habría que cambiar el nombre de las entidades a la primera letra en mayuscula.

2023-03-16 09:38 UTC, alesanfe approved these changes

2023-03-16 09:44 UTC, marvicmar approved these changes
Todo correcto

2023-03-16 09:45 UTC, merged