Task 6(I3): Add session entity
alepervaz/Acme-L3-D02 pull request #49
Opened 2023-03-15 17:58 UTC by alepervaz

2023-03-15 18:18 UTC, marvicmar requested changes
No poner message en las restrinciones

2023-03-15 18:46 UTC, alesanfe requested changes
Los messages impiden cumplir una de las funcionalidades.

2023-03-16 09:20 UTC, marvicmar approved these changes
Tras realizar una correción de las relaciones entre las entidades, ahora esta el código correcto

2023-03-16 09:35 UTC, alesanfe approved these changes

2023-03-16 09:45 UTC, marvicmar approved these changes
Todo correcto

2023-03-16 09:45 UTC, merged