Task 6 (I2): Add entity activities
alepervaz/Acme-L3-D02 pull request #51
Opened 2023-03-15 17:59 UTC by marvicmar

2023-03-15 18:16 UTC, alepervaz approved these changes
el codigo se encuentra completo y de forma correcta

2023-03-15 18:40 UTC, alesanfe requested changes
Creo que debería de ser TIMESTAMP.

2023-03-15 21:38 UTC, alesanfe requested changes
Creo que si acaso faltan los comentarios para indicar cada una de las partes de la entidad.

2023-03-15 22:15 UTC, alesanfe approved these changes

2023-03-16 07:33 UTC, alepervaz approved these changes
todo correcto

2023-03-16 07:33 UTC, merged