Task 7 (i3): assistant dashboard
alepervaz/Acme-L3-D02 pull request #52
Opened 2023-03-15 17:59 UTC by alepervaz

2023-03-15 18:20 UTC, marvicmar requested changes
Eliminar message de las restricciones

2023-03-15 21:52 UTC, alesanfe requested changes
Quitar los mensajes.

2023-03-16 09:27 UTC, marvicmar approved these changes
Todo correcto

2023-03-16 09:30 UTC, alesanfe approved these changes

2023-03-16 09:31 UTC, alesanfe approved these changes

2023-03-16 09:46 UTC, merged