Task 12 (G): Add entity Offer
alepervaz/Acme-L3-D02 pull request #57
Opened 2023-03-15 18:02 UTC by marvicmar

2023-03-15 18:26 UTC, alepervaz approved these changes
el código implementado esta completo y desarrollado de forma correcta

2023-03-15 18:27 UTC, alesanfe requested changes
Las restricciones están mal, el máximo está incluido,

2023-03-15 21:37 UTC, alesanfe approved these changes

2023-03-15 22:12 UTC, alesanfe approved these changes

2023-03-16 07:34 UTC, alepervaz requested changes
faltan getter,setter y entity

2023-03-16 08:06 UTC, alesanfe approved these changes

2023-03-16 09:26 UTC, alepervaz approved these changes
todo correcto

2023-03-16 09:26 UTC, merged