Task 14(G): Creación de la entidad Banner.
alepervaz/Acme-L3-D02 pull request #66
Opened 2023-03-15 18:17 UTC by alesanfe

2023-03-15 18:31 UTC, marvicmar requested changes
Eliminar atributo message de las restricciones y el BannerValidator no se debe entregar en este sprint

2023-03-15 18:32 UTC, alepervaz approved these changes
el código implementado esta completo y desarrollado de forma correcta

2023-03-16 09:29 UTC, alepervaz approved these changes
todo correcto

2023-03-16 09:40 UTC, marvicmar approved these changes
Eliminar posteiormente el validador

2023-03-16 09:41 UTC, merged