Task 7 i5
alepervaz/Acme-L3-D02 pull request #68
Opened 2023-03-15 19:29 UTC by sersansan2

2023-03-15 21:36 UTC, alesanfe reviewed
¿Es la task 7 del estudiante 5 o todas las tareas?

2023-03-16 07:24 UTC, marvicmar requested changes
Revisar los comentarios puestos en los distintos ficheros, hay varias cosas que cambiar

2023-03-16 07:24 UTC, marvicmar commented on src/main/java/acme/entities/course/Lecture.java
El tipo Date no tiene la restricción @Temporal, por otro lado le sobra el @Positive

2023-03-16 07:24 UTC, marvicmar commented on src/main/java/acme/entities/audit/AuditingRecordValidator.java
Los Validator al final no deben ser entregados en esta práctica

2023-03-16 07:24 UTC, marvicmar commented on src/main/java/acme/entities/audit/AuditValidator.java
Los validator no se entregan en esta práctica

2023-03-16 07:24 UTC, marvicmar commented on src/main/java/acme/entities/course/Course.java
Quitar message de las restricciones, OneToMany no se puede usar, debe ser ManyToOne. Por otro lado tú no deberias de subir Course

2023-03-16 07:32 UTC, alesanfe requested changes
Seguir formato, máximo incluido y utilizar MomentHelper.

2023-03-16 07:32 UTC, alesanfe commented on src/main/java/acme/entities/audit/AuditingRecord.java
>  		return Duration.between(this.startAudit.toInstant(), this.endAudit.toInstant());
Esto es mejor con MomentHelper.

2023-03-16 07:32 UTC, alesanfe commented on src/main/java/acme/entities/audit/AuditingRecordValidator.java
> +		if (MomentHelper.isBefore(auditingRecord.getStartAudit(), auditingRecord.getEndAudit()))
Crea variables para almacenar la fecha de inicio y la de fin.

2023-03-16 07:32 UTC, alesanfe commented on src/main/java/acme/entities/course/Course.java
> +	@Pattern(regexp = "[A-Z]{1,3}[0-9]{3}", message = "Letras de A-Z entre 1 y 3 veces, seguidas de tres numeros entre 0 y 9")
Falta ^ al inicio y $ al final.

2023-03-16 07:32 UTC, alesanfe commented on src/main/java/acme/entities/course/Course.java
> +	@Length(max = 76)
Los máximo van incluidos.

2023-03-16 07:32 UTC, alesanfe commented on src/main/java/acme/entities/course/Course.java
> +		final Integer countHandsOn = this.lectures.stream().filter(l -> l.getHandsOn() == true).collect(Collectors.toList()).size();
el == true sobra

2023-03-16 07:32 UTC, alesanfe commented on src/main/java/acme/roles/Lecturer.java
> +	// Serialisation identifier
Poner comentario con el formato del profesor.

2023-03-16 07:32 UTC, alesanfe commented on src/main/java/acme/roles/Lecturer.java
> +	@Length(max = 76)
Máximos van incluidos.

2023-03-16 10:56 UTC, closed without merging